{% set name = "flynt" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flynt-{{ version }}.tar.gz
  sha256: 471b7ff00756678e2912d4261dcbcd8fc1395129b66bf6977f88a3b3ad220c90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flynt = flynt:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    # want to stay noarch: python so adding this for all python
    - tomli >=1.1.0

test:
  imports:
    - flynt
  commands:
    - pip check
    - flynt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ikamensh/flynt
  summary: CLI tool to convert a python project's %-formatted strings to f-strings.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ikamensh/flynt
  doc_url: https://github.com/ikamensh/flynt

extra:
  recipe-maintainers:
    - altheaden
    - xylar
